/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programakademik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/**
 *
 * @author ACER
 */
public class entryNilai extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    public entryNilai() {
        initComponents();
        connection();
        clean();
        isiBp();
        isiKode();
    }
    
    private void connection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbakademik", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clean() {
        vNoBp.setSelectedIndex(-1);
        vKdMtk.setSelectedIndex(-1);
        vNama.setText("");
        vNamaMtk.setText("");

        vNilaiTugas.setText("");
        vNilaiMid.setText("");
        vNilaiSemester.setText("");
        vNilaiAkhir.setText("");
        vNilaiHuruf.setText("");

        vNoBp.requestFocus();
    }

    private void isiBp(){
        try {
            vNoBp.addItem("");
            res = stat.executeQuery("SELECT * FROM mahasiswa");

            while (res.next()) {
                vNoBp.addItem(res.getString("noBp"));
            }
            vNoBp.setSelectedIndex(-1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void isiKode() {
        try {
            vKdMtk.addItem("");
            res = stat.executeQuery("SELECT * FROM matakuliah");

            while (res.next()) {
                vKdMtk.addItem(res.getString("kdMtk"));
            }
            vKdMtk.setSelectedIndex(-1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vNoBp = new javax.swing.JComboBox<>();
        vNama = new javax.swing.JTextField();
        vKdMtk = new javax.swing.JComboBox<>();
        vNamaMtk = new javax.swing.JTextField();
        vNilaiTugas = new javax.swing.JTextField();
        vNilaiMid = new javax.swing.JTextField();
        vNilaiSemester = new javax.swing.JTextField();
        vNilaiAkhir = new javax.swing.JTextField();
        vNilaiHuruf = new javax.swing.JTextField();
        process = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Entry Data Nilai");

        jLabel2.setText("No. BP");

        jLabel3.setText("Kode Matakuliah");

        jLabel4.setText("Nilai Tugas");

        jLabel5.setText("Nilai Mid");

        jLabel6.setText("Nilai Semester");

        jLabel7.setText("Nilai Akhir");

        jLabel8.setText("Nilai Huruf");

        vNoBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNoBpActionPerformed(evt);
            }
        });

        vNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNamaActionPerformed(evt);
            }
        });

        vKdMtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vKdMtkActionPerformed(evt);
            }
        });

        vNamaMtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNamaMtkActionPerformed(evt);
            }
        });

        process.setText("Proses");
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        cancel.setText("Batal");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vKdMtk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(vNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(process))
                                    .addComponent(vNoBp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vNilaiMid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vNilaiSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vNilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit)
                        .addGap(42, 42, 42)
                        .addComponent(delete)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vNama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNamaMtk, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancel)
                        .addGap(18, 18, 18)
                        .addComponent(exit)))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vNoBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vKdMtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNamaMtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vNilaiMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vNilaiSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(process))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vNilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete)
                    .addComponent(cancel)
                    .addComponent(exit))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 540);

        setBounds(0, 0, 546, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void vNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vNamaActionPerformed

    private void vKdMtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vKdMtkActionPerformed
        try {
            res = stat.executeQuery("SELECT * FROM matakuliah WHERE "
                + "kdMtk='" + vKdMtk.getSelectedItem() + "'"
            );
            while (res.next()) {
                vNamaMtk.setText(res.getString("namaMtk"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        try {
            res = stat.executeQuery("SELECT * FROM nilai WHERE "
                + "noBp='" + vNoBp.getSelectedItem() + "' "
                + "AND kdMtk='" + vKdMtk.getSelectedItem() + "'"
            );

            while (res.next()) {
                vNilaiTugas.setText(res.getString("nilaiTugas"));
                vNilaiMid.setText(res.getString("nilaiMid"));
                vNilaiSemester.setText(res.getString("nilaiSemester"));
                vNilaiAkhir.setText(res.getString("nilaiAkhir"));
                vNilaiHuruf.setText(res.getString("nilaiHuruf"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_vKdMtkActionPerformed

    private void vNoBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNoBpActionPerformed
        try {
            res = stat.executeQuery("SELECT * FROM mahasiswa WHERE "
                + "noBp='" + vNoBp.getSelectedItem() + "'"
            );
            while (res.next()) {
                vNama.setText(res.getString("nama"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_vNoBpActionPerformed

    private void vNamaMtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNamaMtkActionPerformed

    }//GEN-LAST:event_vNamaMtkActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            stat.executeUpdate("INSERT INTO nilai VALUES ("
                + "'" + vNoBp.getSelectedItem() + "',"
                + "'" + vKdMtk.getSelectedItem() + "',"
                + "'" + vNilaiTugas.getText() + "',"
                + "'" + vNilaiMid.getText() + "',"
                + "'" + vNilaiSemester.getText() + "',"
                + "'" + vNilaiAkhir.getText() + "',"
                + "'" + vNilaiHuruf.getText() + "'"
                + ")"
            );

            clean();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " + e);
        }

    }//GEN-LAST:event_saveActionPerformed

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed
        Double totalTugas, totalMid, totalSemester, total;

        //nilai angka
        totalTugas = (Double.parseDouble(vNilaiTugas.getText()) * 20) / 100;
        totalMid = (Double.parseDouble(vNilaiMid.getText()) * 30) / 100;
        totalSemester = (Double.parseDouble(vNilaiSemester.getText()) * 50) / 100;

        total = totalTugas + totalMid + totalSemester;
        vNilaiAkhir.setText(String.valueOf(total));
        
        //nilai huruf
        if (total >= 80) {
            vNilaiHuruf.setText("A");
        } else if (total < 80 && total >= 65) {
            vNilaiHuruf.setText("B");
        } else if (total < 65 && total >= 55) {
            vNilaiHuruf.setText("C");
        } else if (total < 55 && total >= 40) {
            vNilaiHuruf.setText("D");
        } else {
            vNilaiHuruf.setText("E");
        }


    }//GEN-LAST:event_processActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            stat.executeUpdate("UPDATE nilai SET "
                + "nilaiTugas='" + vNilaiTugas.getText() + "', "
                + "nilaiMid='" + vNilaiMid.getText() + "', "
                + "nilaiSemester='" + vNilaiSemester.getText() + "', "
                + "nilaiAkhir='" + vNilaiAkhir.getText() + "', "
                + "nilaiHuruf='" + vNilaiHuruf.getText() + "' "
                + "WHERE noBp='" + vNoBp.getSelectedItem() + "' "
                + "AND kdMtk='" + vKdMtk.getSelectedItem() + "'"
            );
            clean();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Diupdate...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            stat.executeUpdate("DELETE FROM nilai WHERE "
                + "noBp='" + vNoBp.getSelectedItem() + "' "
                + "AND kdMtk='" + vKdMtk.getSelectedItem() + "'"
            );
            clean();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pesan salah: " + e);
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        clean();
    }//GEN-LAST:event_cancelActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entryNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entryNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entryNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entryNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entryNilai().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton process;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> vKdMtk;
    private javax.swing.JTextField vNama;
    private javax.swing.JTextField vNamaMtk;
    private javax.swing.JTextField vNilaiAkhir;
    private javax.swing.JTextField vNilaiHuruf;
    private javax.swing.JTextField vNilaiMid;
    private javax.swing.JTextField vNilaiSemester;
    private javax.swing.JTextField vNilaiTugas;
    private javax.swing.JComboBox<String> vNoBp;
    // End of variables declaration//GEN-END:variables
}
